playsound mob.blaze.shoot @s ^^^ 0.2 0.35
playsound dig.sand        @s ^^^ 0.5 0.3
playsound dig.sand        @s ^^^ 0.5 0.5
playsound random.fizz     @s ^^^ 0.2 0.3
playsound random.fizz     @s ^^^ 0.2 0.4
playsound random.fizz     @s ^^^ 0.5 0.5
playsound random.fizz     @s ^^^ 0.5 0.6
playsound random.fizz     @s ^^^ 0.5 0.7
playsound random.fizz     @s ^^^ 0.5 0.8
playsound random.fizz     @s ^^^ 0.5 0.9
playsound random.fizz     @s ^^^ 0.5 1.0